name: krishimithra
description: KrishiMithra – Smart Agriculture Assistant
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🌍 Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.5

  # UI & Icons
  cupertino_icons: ^1.0.8
  oktoast: ^3.3.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0

  # Phone Authentication
  intl_phone_field: ^3.1.0

  # HTTP & Utils
  http: ^1.0.0
  logging: ^1.2.0
  flutter_dotenv: ^5.1.0

  # 📍 Location & Maps
  geolocator: any
  geocoding: ^4.0.0
  url_launcher: ^6.2.6
  google_maps_flutter: ^2.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0

  # Supabase
  supabase_flutter: ^2.0.6
  mime: ^1.0.4
  path: ^1.8.3

  # 💾 Local Storage
  shared_preferences: ^2.2.2

  # Utilities
  uuid: ^4.0.0

  # Image & File Pickers
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  file_picker: ^10.2.0

  # Search & Keyboard
  flutter_typeahead: ^5.2.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # App Assets
    - assets/icons/
    - assets/km.png.png
    - assets/login_bg.png
    - assets/log.png
    - assets/leaves.png
    - assets/farmer_logo.png
    - .env